server:
  port: 8081

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/vueadmin?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 120.24.54.47
    #  password: 15960542908zqh
    port: 6379
  mvc:
    static-path-pattern: /static/**
  servlet:
    multipart:
      enabled: true    #是否启用http请求
      max-file-size: 20MB   #单个文件大小限制
      max-request-size: 100MB  #单次请求大小限制
  rabbitmq:
    host: 120.24.54.47 # 主机名
    port: 5672 # 端口
    virtual-host: / # 虚拟主机
    username: zqh # 用户名
    password: 123456 # 密码

sa-token:
  token-name: vueadmintoken

#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.example.vueadminjava2.entity
